#!/bin/bash

host=127.0.0.1
port=8081
syncHost=127.0.0.1
syncPort=8080

bin/ucoind --currency beta_brousouf --mdb bb2 reset config
bin/ucoind --currency beta_brousouf --mdb bb2 reset data
bin/ucoind --currency beta_brousouf --mdb bb2 config --pgpkey test/data/ubot1.priv --ipv4 $host --port $port --remote4 $host --remotep $port --pgppasswd "ubot1" --kmanagement ALL
bin/ucoind --currency beta_brousouf --mdb bb2 sync $syncHost $syncPort
bin/ucoind --currency beta_brousouf --mdb bb2 allow-key 2E69197FAB029D8669EF85E82457A1587CA0ED9C
bin/ucoind --currency beta_brousouf --mdb bb2 start

