@startuml

(B5_b) as B5f #LightBlue
(B6_b) as B6f #LightBlue

skinparam usecase {
	BackgroundColor DarkSeaGreen
	BorderColor DarkSlateGray
	ArrowColor Blue
}

(B3) -> (B4)
(B4) --> (B5_a)
(B5_a) -> (B6_a)
(B6_a) -> (B7_a)
(B4) -[#LightBlue]> (B5f)
(B5f) -[#LightBlue]> (B6f)

@enduml