#!/bin/bash
jpgp_folder="mvn-jpgp"
rm -Rf "$jpgp_folder"
git clone --branch=master http://github.com/c-geek/jpgp.git "$jpgp_folder"
cd "$jpgp_folder"
mvn clean install
cp target/jpgp-0.0.1-SNAPSHOT.jar ../bin/
cd ../
rm -Rf "$jpgp_folder"