#!/bin/bash

locale_ip=`awk 'NR==7 {print $1}' /etc/hosts`
remote_ip=`curl -s https://4.ifcfg.me/`
if [ -n $DUNITER_SALT ] && [ -n $DUNITER_PASSWD ]; then
  identity_args="--salt $DUNITER_SALT --passwd $DUNITER_PASSWD"
else
  identity_args=""
fi

duniter init --autoconf
duniter config --noupnp --remote4 $remote_ip --ipv4 $locale_ip $identity_args
duniter sync $DUNITER_URL $DUNITER_PORT
duniter start
tail -f /dev/null
