@startuml

skinparam usecase {
	BackgroundColor DarkSeaGreen
	BorderColor DarkSlateGray
	ArrowColor Blue
}

(C1) <-- (C2)
(C1) <-- (C3)
(C2) <-- (C4)
(C2) <-- (C5)
(C3) <-- (C6)
(C3) <-- (C7)
(C4) <-- (C8)
(C4) <-- (C9)
(C5) <-- (C10)
(C5) <-- (C11)
(C6) <-- (C12)
(C6) <-- (C13)
(C7) <-- (C14)
(C7) <-- (C15)

@enduml