#!/bin/bash

DUN_ROOT=/opt/duniter
DUN_SOURCES=$DUN_ROOT/
mkdir -p $DUN_SOURCES

# Duniter sources extraction
if [[ -f $DUN_ROOT/duniter.zip ]]; then
  unzip -q -d $DUN_SOURCES/ $DUN_ROOT/duniter.zip
  rm -rf $DUN_ROOT/duniter.zip
fi

# Duniter-Desktop
if [[ -f $DUN_SOURCES/duniter-desktop ]]; then
  ln -s $DUN_SOURCES/duniter-desktop /usr/bin/duniter-desktop
  # Links for Node + NPM
  cd $DUN_SOURCES
  cd bin
  ln -s ../lib/node_modules/npm/bin/npm-cli.js ./npm -f
  cd ..
  ln -s ./bin/node node -f
  ln -s ./bin/npm npm -f
fi

# Duniter CLI executes with embedded node
if [[ -d $DUN_SOURCES/node ]]; then
  chmod 755 $DUN_SOURCES/bin/duniter
  chmod 755 $DUN_SOURCES/bin/duniter_js
  sed -i "s/usr\/bin\/env node/opt\/duniter\/node\/bin\/node/g" $DUN_SOURCES/bin/duniter_js
  ln -s $DUN_SOURCES/bin/duniter /usr/bin/duniter -f
  ln -s $DUN_SOURCES/bin/duniter_js /usr/bin/duniter_js -f
  cd $DUN_SOURCES
  # Generate bash completion script
  mkdir -p "/etc/bash_completion.d/"
  bin/duniter completions bash > /etc/bash_completion.d/duniter_completion.bash
  cd node/bin/
  ln -s ../lib/node_modules/npm/bin/npm-cli.js ./npm -f
  # Add duniter user for service
  mkdir -p /var/lib/duniter
  adduser --system --quiet --home /var/lib/duniter --no-create-home --disabled-password --group duniter
  chown duniter:duniter /var/lib/duniter
fi
# Else will execute with environment node

chmod +r -R $DUN_ROOT
